repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
- repo: https://github.com/ambv/black
  rev: 22.12.0
  hooks:
  - id: black
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  -   id: reorder-python-imports
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.0.235'
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    name: Run type checks
    args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
